# Generated by Django 5.1.dev20240510224519 on 2024-05-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygovhouseholdincomeandexpenditurestates',
            name='gini',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='mygovhouseholdincomeandexpenditurestates',
            name='poverty',
            field=models.DecimalField(decimal_places=2, default=-0.0, max_digits=20),
        ),
    ]
