# Generated by Django 5.0.6 on 2024-05-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_mygovhouseholdincomeandexpenditurestates_gini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='acronyms',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
